
// This file has been generated by the GUI designer. Do not modify.
namespace PTreeview
{
	public partial class VentanaAñadir
	{
		private global::PTreeview.newRegistro newregistro1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PTreeview.VentanaAñadir
			this.Name = "PTreeview.VentanaAñadir";
			this.Title = global::Mono.Unix.Catalog.GetString ("VentanaAñadir");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PTreeview.VentanaAñadir.Gtk.Container+ContainerChild
			this.newregistro1 = new global::PTreeview.newRegistro ();
			this.newregistro1.Events = ((global::Gdk.EventMask)(256));
			this.newregistro1.Name = "newregistro1";
			this.Add (this.newregistro1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
